// ITEMS
export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_LOADING = 'GET_ITEMS_LOADING';
export const GET_ITEMS_ERROR = 'GET_ITEMS_ERROR';

export const FILTER_ITEMS_BY_TAG_NAME = 'FILTER_ITEMS_BY_TAG_NAME';

export const BORROW_ITEM_SUCCESS = 'BORROW_ITEM_SUCCESS';
export const BORROW_ITEM_LOADING = 'BORROW_ITEM_LOADING';
export const BORROW_ITEM_FAIL = 'BORROW_ITEM_FAIL';

// USERS
export const GET_USERS = 'GET_USERS';
export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

// AUTHENTICATION
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'RESITER_FAIL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// ADD ITEM FORM
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const UPLOAD_IMAGE_LOADING = 'UPLOAD_IMAGE_LOADING';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';
export const UPDATE_TAGS = 'UPDATE_TAGS';
